version: '3'

services:
    alm:
        container_name: alm
        image: devprom/alm
        ports:
            - "80:80"
            - "3306:3306"
        volumes:
            - "./backup:/var/www/devprom/backup"
       networks:
            alm:
                ipv4_address: 172.28.1.1
    plantuml:
        container_name: plantuml
        image: plantuml/plantuml-server
        networks:
            alm:
                ipv4_address: 172.28.1.2
    mathjax:
        container_name: mathjax
        image: devprom/math
        networks:
            alm:
                ipv4_address: 172.28.1.3
networks:
    alm:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/16
